Added history of file analyze
polytech-coronavirus/Executable-Analyzer pull request #27
Opened 2021-11-03 15:09 UTC by pavlyuchenkov-aa

2021-11-04 20:56 UTC, WestFoxy requested changes
Убрать лишние пробелы в коде и пофиксить недочеты

2021-11-04 20:56 UTC, WestFoxy commented on src/HistoryManager.cpp
> +  std::rotate(cachedHistory.rbegin(), cachedHistory.rbegin() + 1, cachedHistory.rend());
А для чего это?

2021-11-04 20:56 UTC, WestFoxy commented on src/HistoryManager.h
> +  std::string historyPath = "analyzeHistory.txt";
Лучше вынести в константу и добавить метод для её получения.

2021-11-04 20:56 UTC, WestFoxy commented on src/HistoryManager.cpp
> +    throw std::runtime_error("Could not create or open history file");
Нету смысла прекращать работу, нужно просто вывести пользователю сообщение о том, что кэш недоступен для чтения/записи/создания.

2021-11-04 21:23 UTC, Rudnitskiy commented on src/foxui.cpp
> +            ImGui::SetItemDefaultFocus();
**Куда пропали скобочки???**

2021-11-04 21:23 UTC, Rudnitskiy commented on src/foxui.cpp
> +  static bool file_dialog_open, load_cached_history = true;
Переменная file_dialog_open не проинициализирована

2021-11-04 21:23 UTC, Rudnitskiy commented on src/HistoryManager.h
> +  std::vector<std::string> getHistory();
Либо возвращать ссылку на вектор, либо сделать метод константным

2021-11-04 21:23 UTC, Rudnitskiy commented on src/foxui.cpp
> +  static std::vector<std::string> cachedHistoryCopy;
Если бы метод `std::vector<std::string> getHistory();` возвращал ссылку, то не нужно было бы здесь копию хранить

2021-11-05 12:11 UTC, nikitasokolov25 reviewed
Молодцы ребята

2021-11-05 21:38 UTC, WestFoxy commented on src/foxui.cpp
> +  static std::vector<std::string> cachedHistoryCopy;
А если класс будет динамическим? Я сохранил ссылку на `std::vector<std::string>` , а после удалил класс, будет же нехорошо

2021-11-05 21:42 UTC, Rudnitskiy commented on src/foxui.cpp
> +  static std::vector<std::string> cachedHistoryCopy;
shared_ptr?

2021-11-05 21:50 UTC, WestFoxy commented on src/foxui.cpp
> +  static std::vector<std::string> cachedHistoryCopy;
Как вариант, но это усложнит код

2021-11-06 00:50 UTC, pavlyuchenkov-aa commented on src/HistoryManager.cpp
> +  std::rotate(cachedHistory.rbegin(), cachedHistory.rbegin() + 1, cachedHistory.rend());
для добавления элемента в начало вектора

2021-11-06 01:22 UTC, WestFoxy approved these changes

2021-11-06 01:22 UTC, merged